name: Auto RC Bump PR on release merge (need-bump)

on:
  pull_request:
    types: [closed]
    branches: [release]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_bump_on_label:
    if: ${{ github.event.pull_request.merged == true && contains(toJSON(github.event.pull_request.labels), 'need-bump') }}
    runs-on: ubuntu-latest

    steps:
      - name: 릴리스 브랜치 체크아웃
        uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0

      - name: 현재 버전 읽기
        id: read_version
        run: |
          CURRENT=$(jq -r .version package.json)
          echo "current_version=$CURRENT" >> $GITHUB_OUTPUT

      - name: 다음 RC 버전 계산
        id: calc
        env:
          CURRENT: ${{ steps.read_version.outputs.current_version }}
        run: |
          BASE=$(echo "$CURRENT" | sed 's/-rc\..*//')
          CUR_RC=$(echo "$CURRENT" | grep -oE 'rc\.[0-9]+' | cut -d. -f2 || echo "")
          if [ -n "$CUR_RC" ]; then
            RC_NUM=$((CUR_RC+1))
            NEXT="${BASE}-rc.${RC_NUM}"
          else
            NEXT="${BASE}-rc.1"
          fi
          echo "next_version=$NEXT" >> $GITHUB_OUTPUT

      - name: 버전 변경 준비
        env:
          NEXT: ${{ steps.calc.outputs.next_version }}
        run: |
          jq ".version = \"${NEXT}\"" package.json > tmp && mv tmp package.json
          if [ -f package-lock.json ]; then
            jq ".version = \"${NEXT}\"" package-lock.json > tmp && mv tmp package-lock.json
          fi

      - name: PR 생성 (release)
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "bump: ${{ steps.calc.outputs.next_version }}"
          title: "bump: ${{ steps.calc.outputs.next_version }} → release"
          body: |
            need-bump 라벨 기반 자동 생성된 RC bump PR입니다.
            - version: `${{ steps.calc.outputs.next_version }}`
            - from: PR #${{ github.event.pull_request.number }}
          base: release
          branch: bump/release-${{ steps.calc.outputs.next_version }}
          labels: bump, rc


