name: main 브랜치 push 시 버전 finalize PR 생성

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  finalize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with: { ref: main, fetch-depth: 0 }

      - name: Detect RC and compute final
        id: detect
        run: |
          CUR=$(jq -r .version package.json || echo "")
          echo "cur=$CUR" >> $GITHUB_OUTPUT
          if [[ "$CUR" =~ -rc\.[0-9]+$ ]]; then
            BASE=${CUR%%-rc.*}
            echo "is_rc=true" >> $GITHUB_OUTPUT
            echo "final=$BASE" >> $GITHUB_OUTPUT
          else
            echo "is_rc=false" >> $GITHUB_OUTPUT
            echo "final=$CUR" >> $GITHUB_OUTPUT
          fi

      - name: Create finalize PR branch and open PR
        if: steps.detect.outputs.is_rc == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FINAL="${{ steps.detect.outputs.final }}"
          BR="finalize/v${FINAL}"

          # 브랜치 생성
          git checkout -b "$BR"

          # 버전 strip(-rc)
          jq ".version = \"${FINAL}\"" package.json > tmp && mv tmp package.json
          if [ -f package-lock.json ]; then
            jq ".version = \"${FINAL}\"" package-lock.json > tmp && mv tmp package-lock.json
            git add package.json package-lock.json
          else
            git add package.json
          fi

          git -c user.name="github-actions" -c user.email="actions@github.com" commit -m "finalize: v${FINAL}"
          git push origin "$BR"

          # 기존 PR 있으면 skip
          if gh pr view --base main --head "$BR" >/dev/null 2>&1; then
            echo "Existing finalize PR found. Skipping create."
          else
            TITLE="finalize: v${FINAL}"
            BODY=$'main 보호 설정으로 인한 finalize PR입니다.\n- 최종 버전: '"v${FINAL}"$'\n- 작업: rc 스트립'
            gh pr create \
              --base main \
              --head "$BR" \
              --title "$TITLE" \
              --body "$BODY" \
              --label finalize
          fi

      # 기존 'sync PR'은 필요 시 유지/조정
