name: Finalize version on main & sync back

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  finalize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with: { ref: main, fetch-depth: 0 }

      - name: Detect RC and compute final
        id: detect
        run: |
          CUR=$(jq -r .version package.json || echo "")
          echo "cur=$CUR" >> $GITHUB_OUTPUT
          if [[ "$CUR" =~ -rc\.[0-9]+$ ]]; then
            BASE=${CUR%%-rc.*}         # strip -rc.N
            echo "is_rc=true" >> $GITHUB_OUTPUT
            echo "final=$BASE" >> $GITHUB_OUTPUT
          else
            echo "is_rc=false" >> $GITHUB_OUTPUT
            echo "final=$CUR" >> $GITHUB_OUTPUT

      - name: Finalize version commit (strip -rc)
        if: steps.detect.outputs.is_rc == 'true'
        run: |
          FINAL="${{ steps.detect.outputs.final }}"
          jq ".version = \"${FINAL}\"" package.json > tmp && mv tmp package.json
          if [ -f package-lock.json ]; then
            jq ".version = \"${FINAL}\"" package-lock.json > tmp && mv tmp package-lock.json
            git add package.json package-lock.json
          else
            git add package.json
          fi
          git -c user.name="github-actions" -c user.email="actions@github.com" \
            commit -m "set: ${FINAL}"
          git push origin HEAD:main

      - name: Create prod tag & (optional) GitHub Release
        run: |
          FINAL="${{ steps.detect.outputs.final }}"
          git tag -a "v${FINAL}" -m "Release v${FINAL}"
          git push origin "v${FINAL}"
        # (옵션) release-drafter/changesets 연계 가능

      - name: Open sync PR main -> release (single shot)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 이미 동일한 PR이 열려 있으면 스킵
          if gh pr view --base release --head main >/dev/null 2>&1; then
            echo "Existing PR main -> release found. Skipping create."
          else
            gh pr create \
              --base release \
              --head main \
              --title "sync: main -> release (v${{ steps.detect.outputs.final }})" \
              --body "배포 직후 동기화 PR입니다. 머지 후 다음 RC를 준비하세요." \
              --label sync
          fi
